### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by rlaurika** [elixir-cloud-aai/proTES#3]
**Is your feature request related to a problem? Please describe.**

For production, it should be possible to deploy proTES on Kubernetes.

**Describe the solution you'd like**

Create a new deployment subdirectory that contains documentation on how to deploy proTES on Kubernetes and contains the necessary YAML files for deployment.

**Describe alternatives you've considered**

Not applicable.

**Additional context**

The same YAML templates should be usable for both vanilla Kubernetes and OpenShift. We can have a set of common files and then files specific to OpenShift (e.g. Route) and Kubernetes (e.g. NGINX ingress setup).

**Comment by rlaurika** [comment]
I've created a new branch called `k8s_deployment` for this. Right now it only has the basic directory structure, some untested YAML file templates that need to be modified and an almost empty README.md file.

**Comment by jdbohrman** [comment]
I'd love to help with this also if the project owners are open to the assistance...

**Comment by uniqueg** [comment]
@jdbohrman: Very gladly! Sorry for the late reply, I only saw your message just now. I've been too busy with other things for a little while, but from February on working on proTES is going to be a priority again. Anything in particular that you'd like to help with?

**Comment by uniqueg** [comment]
Do analogous to pull requests 91 (elixir-europe/WES-ELIXIR/pull/91) to 96 (elixir-europe/WES-ELIXIR/pull/96) in https://github.com/elixir-europe/WES-ELIXIR

**Comment by uniqueg** [comment]
I think this had been resolved, but certainly is now with #112
