### ISSUE TITLE
Set JWT in Snakemake call for accessing TES server

### ISSUE THREAD

**Issue by vinjana** [elixir-cloud-aai/proTES#94]
Snakemake takes a `--tes` parameter or allows setting this the TES access via the `--profile` files, but that does not include authentication to the TES server.

Implement in Snakemake a way to pass a JWT to the TES server.

**Comment by vinjana** [comment]
https://gitlab.com/one-touch-pipeline/weskit/api/-/issues/290

**Comment by svedziok** [comment]
PR is open and waiting for review
https://github.com/snakemake/snakemake/pull/1966

**Comment by uniqueg** [comment]
This seems to be done 🥳
